<?php
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: Magiccart<team.magiccart@gmail.com>
 * @@Create Date: 2014-08-08 22:57:12
 * @@Modify Date: 2016-03-04 17:22:21
 * @@Function:
 */
 ?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $helpLabels = $this->helper('alothemes/labels');
    $catId = $this->getActive();
    if(is_null($catId)) $catId = $this->getRequest()->getParam('type');
?>

<div class="mage-magictabs mc-<?php echo $catId;?>">
    <?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
    <?php 
        $config = $this->getWidgetCfg(); 
        $width  = $config['widthImages'];
        $height  = $config['heightImages'];
        $actions = isset($config['action']) ? $config['action'] : array();
    ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_rowCount = isset($config['row']) ? $config['row'] : 1; //$this->getColumnCount(); ?>
    <?php $j=0; $time = isset($config['productDelay']) ? $config['productDelay'] : 0; ?>
    <?php $tag = ($_rowCount >1) ? 'div' : 'ul'; ?>
    <<?php echo $tag ?> class="flexisel-content products-grid <?php echo $catId;?> zoomOut play">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($_rowCount > 1 && $i++%$_rowCount==0): ?>
            <ul class="products-grid-rows">
        <?php endif ?>
            <?php $t = $j*$time; $t .='ms'; $j++; ?>

                <li style="<?php echo "-webkit-animation-delay:$t;-moz-animation-delay:$t;-o-animation-delay:$t;animation-delay:$t" ?>;" class="item item-animate">
                    <div class="per-product">
                        <?php echo $helpLabels->getLabels($_product); //Product labels ?>
                        <div class="images-container">
						    <div class="product-hover">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
									<img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($width , $height); ?>" width="<?php echo $width ?>" height="<?php echo $height ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
								
								   <?php $imagehv = $_product->load('media_gallery')->getMediaGalleryImages()->getItemByColumnValue('position','2');
									if($imagehv): $imagehv = $imagehv->getFile();
									?>
										<span class="product-img-back">
											<img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image', $imagehv)->resize($width , $height); ?>" width="<?php echo $width ?>" height="<?php echo $height ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
										</span>
									<?php endif ?>
								</a>
								<a title="<?php echo $this->__('Quick View') ?>" href="<?php echo $this->getUrl('magicshop/quickview/view') .'id/'.$_product->getId()?>" class="link-quickview"><span class="lnr lnr-link"></span>
								</a>
							</div> 
                           
                        </div>
                        <div class="products-textlink clearfix">
                            <div class="display-table">
                                <div class="table-cell">
                                    <h2 class="product-name">
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                                    </h2>
                                   
                                </div>
								<div class="hover-acctions">
									<div class="hover-price">
										<?php if(in_array("review", $actions)):?>
										   <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
										<?php endif ?>
										<?php echo $this->getPriceHtml($_product, true) ?>
									</div>
									<div class="actions-no hover-box">
										<div class="actions">
										<div class="display-block">
											<?php if(in_array("cart", $actions)):?>
												<?php if($_product->isSaleable()): ?>
													<div class="actions-cart">
														<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart pull-left-none" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span>
														</button>
													</div>
												<?php else: ?>
													<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span>
													</p>
												<?php endif; ?>
											<?php endif; ?>
											<ul class="add-to-links pull-left-none">
											   <?php if(in_array("wishlist", $actions)):?>
													<?php if ($this->helper('wishlist')->isAllow()) : ?>
														<li class="pull-left-none pull-wishlist"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><span class="lnr lnr-heart"></span></a></li>
													<?php endif; ?>
												<?php endif; ?>

												<?php if(in_array("compare", $actions)):?>
													<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
														<li class="pull-left-none pull-compare"><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" class="link-compare"><span class="lnr lnr-layers"></span></a></li>
													<?php endif; ?>
												<?php endif; ?>
												
											</ul>
										</div>
										</div>
									</div>
									
									
								</div>
                            </div>
							
                             <!--<div class="display-show">
                                <h2 class="product-name">
                                    <a href="<?php //echo $_product->getProductUrl() ?>" title="<?php //echo $this->stripTags($_product->getName(), null, true) ?>"><?php //echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                                </h2>
                                 <?php if(in_array("review", $actions)):?>
                                   <?php //echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                <?php endif ?>
                                <?php //echo $this->getPriceHtml($_product, true) ?>
                            </div>-->
                         </div>
    				</div>
                </li>
            <?php if ($_rowCount > 1 && $i%$_rowCount==0 || $i==$_collectionSize): ?>
                </ul>
            <?php endif ?>
        <?php endforeach ?>
    </<?php echo $tag; ?>>
<?php endif; ?>
</div>


